import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/enhanced/header";
import Footer from "@/components/enhanced/footer";
import Background from "@/components/enhanced/background";

export const dynamic = 'force-dynamic'; // force runtime rendering

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dqnut Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white min-h-screen flex flex-col`}
      >
        <Background />
        <Header />

        <main className="container mx-auto px-5 py-8 flex-grow">
            {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
